package jdbc.form;

import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class MyWin extends javax.swing.JFrame implements ActionListener {
     
    public MyWin() throws SQLException {
        initComponents();
        this.fillTable(1);
        this.IDasc.setSelected(true);
        this.IDdesc.addActionListener(this);
        this.IDasc.addActionListener(this);
        this.CompanyNameASC.addActionListener(this);
        this.CompanyNameDESC.addActionListener(this);
        this.ContactNameASC.addActionListener(this);
        this.ContactNameDESC.addActionListener(this);
    }

    public void fillTable(int order) throws SQLException {
        currOder = order;
        String ID="";
        boolean selected=false;
        if(Tabela.getSelectedRow()>=0) {
            ID = (String)cm.getValueAt(Tabela.getSelectedRow(), 0);
            selected = true;
        }
        
        this.Tabela.repaint();
        cm = (CustomerModel) this.Tabela.getModel();
        cm.reset();
        try {
            Connection con = DriverManager.getConnection(this.connectionUrl);
            
            CallableStatement MainStatment = con.prepareCall("{call filltable(?)}");
            
            MainStatment.setInt(1, order);
            ResultSet result = MainStatment.executeQuery();
            
            while (result.next()) {
            	cm.addCustomer(new Customer(result.getString(1), result.getString(2), result.getString(3), 
                                            result.getString(4), result.getString(5), result.getString(6), 
                                            result.getString(7), result.getString(8), result.getString(9), 
                                            result.getString(10),result.getString(11)));
            }
            if(selected) {
                CallableStatement SelectStatment = con.prepareCall("{call rownum(?,?)}");
                SelectStatment.setString(1, ID);
                SelectStatment.setInt(2, order);
                
                result = SelectStatment.executeQuery();
                if(result.next()) {
                    Tabela.clearSelection();
                    Tabela.setRowSelectionInterval(result.getInt(1)-1, result.getInt(1)-1);
                    Tabela.scrollRectToVisible(new Rectangle(Tabela.getCellRect(result.getInt(1)-1, 0, true)));
                }               
            }
            
       con.close();
       } catch (SQLException ex) {
            Logger.getLogger(MyWin.class.getName()).log(Level.SEVERE, null, ex);
       }
    }        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        New = new javax.swing.JButton();
        bClear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        IDasc = new javax.swing.JRadioButton();
        IDdesc = new javax.swing.JRadioButton();
        CompanyNameASC = new javax.swing.JRadioButton();
        CompanyNameDESC = new javax.swing.JRadioButton();
        ContactNameASC = new javax.swing.JRadioButton();
        ContactNameDESC = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        CompanyName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ContactTitle = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ContactName = new javax.swing.JTextField();
        CustomerID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Adress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Country = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        City = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Region = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        PostalCode = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Phone = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Fax = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(890, 500));

        Tabela.setModel(new CustomerModel());
        Tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabela);

        Update.setText("Update");
        Update.setPreferredSize(new java.awt.Dimension(57, 23));
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Delete.setText("Delete");
        Delete.setPreferredSize(new java.awt.Dimension(67, 23));
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        New.setText("New");
        New.setPreferredSize(new java.awt.Dimension(67, 23));
        New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewActionPerformed(evt);
            }
        });

        bClear.setText("Clear");
        bClear.setPreferredSize(new java.awt.Dimension(67, 23));
        bClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClearActionPerformed(evt);
            }
        });

        jLabel1.setText("OrderBy");

        buttonGroup1.add(IDasc);
        IDasc.setText("> CustomerID");

        buttonGroup1.add(IDdesc);
        IDdesc.setText("< CustomerID");

        buttonGroup1.add(CompanyNameASC);
        CompanyNameASC.setText("> Company Name");

        buttonGroup1.add(CompanyNameDESC);
        CompanyNameDESC.setText("< Company Name");

        buttonGroup1.add(ContactNameASC);
        ContactNameASC.setText("> Contact Name");

        buttonGroup1.add(ContactNameDESC);
        ContactNameDESC.setText("> Contact Name");

        jLabel3.setText("CompanyName");

        jLabel4.setText("ContactTitle");

        jLabel5.setText("ContactName");

        CustomerID.setEditable(false);

        jLabel2.setText("CustomerID");

        jLabel6.setText("Adress");

        jLabel7.setText("Country");

        jLabel8.setText("City");

        jLabel9.setText("Region");

        jLabel10.setText("PostalCode");

        jLabel11.setText("Phone");

        jLabel12.setText("Fax");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Region, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel12)
                        .addGap(10, 10, 10)
                        .addComponent(Fax))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ContactName)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Adress))
                            .addComponent(CompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ContactTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Country)))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(ContactTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ContactName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(Adress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(Country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(Region, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(PostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(Fax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Delete, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(New, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IDasc)
                            .addComponent(IDdesc))
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CompanyNameDESC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ContactNameDESC))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CompanyNameASC)
                                .addGap(69, 69, 69)
                                .addComponent(ContactNameASC))))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(New, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDasc, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CompanyNameASC)
                    .addComponent(ContactNameASC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDdesc)
                    .addComponent(CompanyNameDESC)
                    .addComponent(ContactNameDESC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaMouseClicked
        Customer c = (Customer)cm.customers.get(Tabela.convertRowIndexToModel(Tabela.getSelectedRow()));
        this.CompanyName.setText(c.CompanyName);
        this.Adress.setText(c.Address);
        this.City.setText(c.City);
        this.ContactName.setText(c.ContactName);
        this.ContactTitle.setText(c.ContactTitle);
        this.Country.setText(c.Country);
        this.CustomerID.setText(c.CustomerID);
        this.Fax.setText(c.Fax);
        this.Region.setText(c.Region);
        this.PostalCode.setText(c.PostalCode);
        this.Phone.setText(c.Phone);
    }//GEN-LAST:event_TabelaMouseClicked

    private void NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewActionPerformed
        Connection con;
        Validation validate = new Validation(true);
        String newID="";
        
        try {
            con = DriverManager.getConnection(this.connectionUrl);
            
            CallableStatement cStmt = con.prepareCall("{call newid_proc()}");

            ResultSet result = cStmt.executeQuery();
            if(result.next())
            {
                newID = result.getString(1);
            }
            
            if(!this.validation()) return;
            
            cStmt = con.prepareCall("{call insert_proc(?,?,?,?,?,?,?,?,?,?,?)}");
            cStmt.setString(1, newID);
            cStmt.setString(2, this.CompanyName.getText());
            cStmt.setString(3, this.ContactName.getText());
            cStmt.setString(4, this.ContactTitle.getText());
            cStmt.setString(5, this.Adress.getText());
            cStmt.setString(6, this.City.getText());
            cStmt.setString(7, this.Region.getText());
            cStmt.setString(8, this.PostalCode.getText());
            cStmt.setString(9, this.Country.getText());
            cStmt.setString(10, this.Phone.getText());
            cStmt.setString(11, this.Fax.getText());
            cStmt.execute();
            
            cStmt = con.prepareCall("{call rownum(?,?)}");
            cStmt.setString(1, newID);
            cStmt.setInt(2, currOder);
                
            result = cStmt.executeQuery();
            
            this.fillTable(this.currOder);
            if(result.next())
            {
                Tabela.clearSelection();
                Tabela.setRowSelectionInterval(result.getInt(1)-1, result.getInt(1)-1);      
                Tabela.scrollRectToVisible(new Rectangle(Tabela.getCellRect(result.getInt(1), 0, true)));
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Problem with server connection", "Connection Error", 0);
            Logger.getLogger(MyWin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_NewActionPerformed

    private void bClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClearActionPerformed
        this.clear();
    }//GEN-LAST:event_bClearActionPerformed

    private void clear()
    {
        this.CompanyName.setText("");
        this.Adress.setText("");
        this.City.setText("");
        this.ContactName.setText("");
        this.ContactTitle.setText("");
        this.Country.setText("");
        this.CustomerID.setText("");
        this.Fax.setText("");
        this.Region.setText("");
        this.PostalCode.setText("");
        this.Phone.setText("");
    }
    
    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        Connection con;
        try {
            con = DriverManager.getConnection(this.connectionUrl);
            CallableStatement cStmt = con.prepareCall("{call delete_proc(?)}");
            cStmt.setString(1, this.CustomerID.getText());
            
            cStmt.execute();
            int sel = Tabela.getSelectedRow();
            if((sel+1)==cm.customers.size()) {
                Tabela.setRowSelectionInterval(sel,sel-1);
            }
            this.clear();
            this.fillTable(this.currOder);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Problem with server connection during deleting item", "Connection Error", 0);
            Logger.getLogger(MyWin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        Connection con;
        try {
            if(!this.validation()) return;
            
            con = DriverManager.getConnection(this.connectionUrl);
            CallableStatement MainStatment = con.prepareCall("{call update_proc(?,?,?,?,?,?,?,?,?,?,?)}");
            MainStatment.setString(1, this.CustomerID.getText());
            MainStatment.setString(2, this.CompanyName.getText());
            MainStatment.setString(3, this.ContactName.getText());
            MainStatment.setString(4, this.ContactTitle.getText());
            MainStatment.setString(5, this.Adress.getText());
            MainStatment.setString(6, this.City.getText());
            MainStatment.setString(7, this.Region.getText());
            MainStatment.setString(8, this.PostalCode.getText());
            MainStatment.setString(9, this.Country.getText());
            MainStatment.setString(10, this.Phone.getText());
            MainStatment.setString(11, this.Fax.getText());
            MainStatment.execute();

            this.fillTable(this.currOder);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Problem with server connection during updating item", "Connection Error", 0);           
            Logger.getLogger(MyWin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_UpdateActionPerformed

    @Override
    public void actionPerformed(ActionEvent e) {
        int fillType = 1;
        try {
            if(IDasc.isSelected()) {
                fillType = 1;
            } 
            else if(IDdesc.isSelected()) {
                fillType = 2;
            }
            else if(CompanyNameASC.isSelected())  {
               fillType = 3;
            }
            else if(CompanyNameDESC.isSelected()) {
                fillType = 4;
            }
            else if(ContactNameASC.isSelected())  {
                fillType = 5;
            }
            else if(ContactNameDESC.isSelected()) {
                fillType = 6;
            }
            
            this.fillTable(fillType);
        } catch (SQLException ex) {
                Logger.getLogger(MyWin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void centreWindow() {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        this.setLocation(x, y);
    }
    
    public boolean validation() {
        Validation validate = new Validation(true);
        
            if(!validate.isAlphaNum(this.CompanyName.getText())) {
                validate.messages.addLast("Incorrect company name");
            }
            
            if(!validate.isAlphaNum(this.ContactTitle.getText())) {
                validate.messages.addLast("Incorrect contact title");
            }
            
            if(!validate.isAlphaNum(this.ContactName.getText())) {
                validate.messages.addLast("Incorrect contact name");
            }
            
            if(!validate.isAlphaNum(this.Adress.getText())) {
                validate.messages.addLast("Incorrect adress");
            }
            
            if(!validate.isLetters(this.Country.getText())) {
                validate.messages.addLast("Incorrect country");
            }
            
            if(!validate.isLetters(this.City.getText())) {
                validate.messages.addLast("Incorrect city");
            }
            
            if(!validate.isLetters(this.Region.getText())) {
                validate.messages.addLast("Incorrect region");
            }
            
            if(!validate.isAlphaNum(this.PostalCode.getText())) {
                validate.messages.addLast("Incorrect postal code");
            }
            
            if(!validate.isNum(this.Phone.getText())) {
                validate.messages.addLast("Incorrect phone number");
            }
            
            if(!validate.isNum(this.Fax.getText())) {
                validate.messages.addLast("Incorrect fax number");
            }           
            
            
            if(!validate.correct) {
                JOptionPane.showMessageDialog(null, validate.messages.getFirst(), validate.title, 0);
            }
            
            return validate.correct;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MyWin().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(MyWin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Adress;
    private javax.swing.JTextField City;
    private javax.swing.JTextField CompanyName;
    private javax.swing.JRadioButton CompanyNameASC;
    private javax.swing.JRadioButton CompanyNameDESC;
    private javax.swing.JTextField ContactName;
    private javax.swing.JRadioButton ContactNameASC;
    private javax.swing.JRadioButton ContactNameDESC;
    private javax.swing.JTextField ContactTitle;
    private javax.swing.JTextField Country;
    private javax.swing.JTextField CustomerID;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField Fax;
    private javax.swing.JRadioButton IDasc;
    private javax.swing.JRadioButton IDdesc;
    private javax.swing.JButton New;
    private javax.swing.JTextField Phone;
    private javax.swing.JTextField PostalCode;
    private javax.swing.JTextField Region;
    private javax.swing.JTable Tabela;
    private javax.swing.JButton Update;
    private javax.swing.JButton bClear;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    public CustomerModel cm;
    public int currOder;
    public String connectionUrl = "jdbc:sqlserver://localhost;database=Northwind;integratedSecurity=true;allowMultiQueries=true";
    
}
